[package]
name = "rust-artnet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1"
yew = "0.17"
wasm-bindgen = "0.2.67"